controller_manager:
  ros__parameters:
    update_rate: 1000  
    use_sim_time: true
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    front_steering_position_controller:
      type: position_controllers/JointGroupPositionController

    rear_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

front_steering_position_controller:
  ros__parameters:
    joints:
      - front_left_steering_joint
      - front_right_steering_joint
    command_interfaces: [position]
    state_interfaces: [position, velocity]

rear_wheel_velocity_controller:
  ros__parameters:
    joints:
      - rear_left_wheel_joint
      - rear_right_wheel_joint
    command_interfaces: [velocity]
    state_interfaces: [position, velocity]
